export enum PassStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  ACTIVE = 'ACTIVE',
  EXPIRED = 'EXPIRED',
  SUSPENDED = 'SUSPENDED',
  CANCELLED = 'CANCELLED',
}

export enum PassCategory {
  MONTHLY_GENERAL = 'MONTHLY_GENERAL',
  STUDENT = 'STUDENT',
  SENIOR_CITIZEN = 'SENIOR_CITIZEN',
  DISABLED = 'DISABLED',
}
