apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-conf
  labels:
    app: opentelemetry
    component: otel-collector-conf
spec:
  data:
    otel-collector-config: |
      receivers:
        otlp:
          protocols:
            grpc:
            http:
      processors:
        batch:
        memory_limiter:
          check_interval: 1s
          limit_mib: 4000
          spike_limit_mib: 800
      exporters:
        prometheus:
          endpoint: "0.0.0.0:8889"
        jaeger:
          endpoint: "jaeger-collector.observability.svc.cluster.local:14250"
          tls:
            insecure: true
        loki:
          endpoint: "http://loki.observability.svc.cluster.local:3100/loki/api/v1/push"
      service:
        pipelines:
          traces:
            receivers: [otlp]
            processors: [memory_limiter, batch]
            exporters: [jaeger]
          metrics:
            receivers: [otlp]
            processors: [memory_limiter, batch]
            exporters: [prometheus]
          logs:
            receivers: [otlp]
            processors: [memory_limiter, batch]
            exporters: [loki]
