export enum CrewStatus {
  AVAILABLE = 'AVAILABLE',
  ASSIGNED = 'ASSIGNED',
  CHECKED_IN = 'CHECKED_IN',
  ON_DUTY = 'ON_DUTY',
  CHECKED_OUT = 'CHECKED_OUT',
  ON_LEAVE = 'ON_LEAVE',
  MEDICAL_HOLD = 'MEDICAL_HOLD',
  LICENSE_EXPIRED = 'LICENSE_EXPIRED',
}

export enum CrewRole {
  DRIVER = 'DRIVER',
  CONDUCTOR = 'CONDUCTOR',
}
