export enum MaintenanceStatus {
  SCHEDULED = 'SCHEDULED',
  ASSIGNED = 'ASSIGNED',
  IN_PROGRESS = 'IN_PROGRESS',
  QUALITY_CHECK = 'QUALITY_CHECK',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum JobType {
  PREVENTIVE = 'PREVENTIVE',
  BREAKDOWN = 'BREAKDOWN',
  FITNESS_CERTIFICATION = 'FITNESS_CERTIFICATION',
}
